# Generated by Django 3.1 on 2023-07-13 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psgcCode', models.CharField(blank=True, default=None, help_text='PSGC Code', max_length=50, null=True)),
                ('regDesc', models.CharField(blank=True, default=None, help_text='Region Name', max_length=150, null=True)),
                ('regCode', models.IntegerField(help_text='Reg Code')),
                ('population', models.CharField(blank=True, default=None, help_text='Population', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Region',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psgcCode', models.CharField(blank=True, default=None, help_text='PSGC Code', max_length=50, null=True)),
                ('provDesc', models.CharField(blank=True, default=None, help_text='Province Name', max_length=150, null=True)),
                ('provCode', models.IntegerField(help_text='Provincial Code')),
                ('population', models.CharField(blank=True, default=None, help_text='Population', max_length=50, null=True)),
                ('regCode', models.ForeignKey(help_text='Region', on_delete=django.db.models.deletion.CASCADE, to='location.region')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Province',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psgcCode', models.CharField(blank=True, default=None, help_text='PSGC Code', max_length=50, null=True)),
                ('cityDesc', models.CharField(blank=True, default=None, help_text='City Name', max_length=150, null=True)),
                ('provCode', models.IntegerField(editable=False, help_text='Provincial Code')),
                ('cityCode', models.IntegerField(help_text='City Code')),
                ('population', models.CharField(blank=True, default=None, help_text='Population', max_length=50, null=True)),
                ('provId', models.ForeignKey(help_text='Province', on_delete=django.db.models.deletion.CASCADE, to='location.province')),
                ('regCode', models.ForeignKey(help_text='Region', on_delete=django.db.models.deletion.CASCADE, to='location.region')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'City',
                'ordering': ['id'],
            },
        ),
    ]
