# Generated by Django 3.1 on 2023-07-13 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingsConducted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, help_text='Date', max_length=150, null=True)),
                ('yearDate', models.CharField(blank=True, choices=[('2030', '2030'), ('2029', '2029'), ('2028', '2028'), ('2027', '2027'), ('2026', '2026'), ('2025', '2025'), ('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000'), ('1999', '1999'), ('1998', '1998'), ('1997', '1997'), ('1996', '1996'), ('1995', '1995'), ('1994', '1994'), ('1993', '1993'), ('1992', '1992'), ('1991', '1991'), ('1990', '1990')], default=None, help_text='Year', max_length=4, null=True)),
                ('activityTitle', models.TextField(blank=True, default=None, help_text='Title of Activity', null=True)),
                ('topics', models.CharField(blank=True, default=None, help_text='Topics', max_length=200, null=True)),
                ('municipality', models.ForeignKey(blank=True, db_column='municipality', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings_conducted_municipality', to='location.city')),
                ('province', models.ForeignKey(blank=True, db_column='province', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings_conducted_province', to='location.province')),
            ],
            options={
                'verbose_name': 'Trainings Conducted',
                'verbose_name_plural': 'Trainings Conducted',
                'ordering': ['province', 'municipality', 'yearDate'],
            },
        ),
        migrations.CreateModel(
            name='TrainingsAttended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, help_text='Date', max_length=150, null=True)),
                ('yearDate', models.CharField(blank=True, choices=[('2030', '2030'), ('2029', '2029'), ('2028', '2028'), ('2027', '2027'), ('2026', '2026'), ('2025', '2025'), ('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000'), ('1999', '1999'), ('1998', '1998'), ('1997', '1997'), ('1996', '1996'), ('1995', '1995'), ('1994', '1994'), ('1993', '1993'), ('1992', '1992'), ('1991', '1991'), ('1990', '1990')], default=None, help_text='Year', max_length=4, null=True)),
                ('activityTitle', models.TextField(blank=True, default=None, help_text='Title of Activity', null=True)),
                ('topics', models.CharField(blank=True, default=None, help_text='Topics', max_length=200, null=True)),
                ('trainingImplementer', models.CharField(blank=True, default=None, help_text='Training Implementer', max_length=2500, null=True)),
                ('municipality', models.ForeignKey(blank=True, db_column='municipality', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings_attended_municipality', to='location.city')),
                ('province', models.ForeignKey(blank=True, db_column='province', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings_attended_province', to='location.province')),
            ],
            options={
                'verbose_name': 'Trainings Attended',
                'verbose_name_plural': 'Trainings Attended',
                'ordering': ['province', 'municipality', 'yearDate'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionsAwardsReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAwarded', models.CharField(blank=True, help_text='Date Awarded', max_length=20, null=True)),
                ('titleOfAward', models.CharField(blank=True, default=None, help_text='Title of Award', max_length=500, null=True)),
                ('awardingBody', models.CharField(blank=True, default=None, help_text='Awarding Body', max_length=300, null=True)),
                ('category', models.CharField(blank=True, default=None, help_text='Category', max_length=50, null=True)),
                ('awardeeName', models.CharField(blank=True, default=None, help_text='Awardee Name', max_length=50, null=True)),
                ('municipality', models.ForeignKey(blank=True, db_column='municipality', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recognitions_awards_received_municipality', to='location.city')),
                ('province', models.ForeignKey(blank=True, db_column='province', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recognitions_awards_received_province', to='location.province')),
            ],
            options={
                'verbose_name': 'Recognitions Awards Received',
                'verbose_name_plural': 'Recognitions Awards Received',
                'ordering': ['province', 'municipality', 'dateAwarded'],
            },
        ),
        migrations.CreateModel(
            name='ProvinceCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.TextField(blank=True, default=None, help_text='Coordinates', null=True)),
                ('province', models.ForeignKey(blank=True, db_column='province', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province_coordinate_province', to='location.province')),
            ],
            options={
                'verbose_name': 'Coordinates - Province',
                'verbose_name_plural': 'Coordinates - Province',
                'ordering': ['province'],
            },
        ),
        migrations.CreateModel(
            name='ProductionSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearDate', models.CharField(choices=[('2030', '2030'), ('2029', '2029'), ('2028', '2028'), ('2027', '2027'), ('2026', '2026'), ('2025', '2025'), ('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000'), ('1999', '1999'), ('1998', '1998'), ('1997', '1997'), ('1996', '1996'), ('1995', '1995'), ('1994', '1994'), ('1993', '1993'), ('1992', '1992'), ('1991', '1991'), ('1990', '1990')], help_text='Year', max_length=4)),
                ('activityTitle', models.TextField(blank=True, default=None, help_text='Title of Activity', null=True)),
                ('leadImplementer', models.CharField(blank=True, default=None, help_text='Lead Implementer', max_length=200, null=True)),
                ('agencyName', models.CharField(blank=True, default=None, help_text='Name of Agency', max_length=250, null=True)),
                ('category', models.CharField(blank=True, default=None, help_text='Category', max_length=250, null=True)),
                ('subCategory', models.CharField(blank=True, default=None, help_text='Sub-Category', max_length=250, null=True)),
                ('monthdayDate', models.CharField(blank=True, default=None, help_text='The month and day when the activity is conducted', max_length=50, null=True)),
                ('noOfUnits', models.TextField(blank=True, default=None, help_text='Number of units', null=True)),
                ('weightPerBag', models.TextField(blank=True, default=None, help_text='If category is seeds or fertilizer, specify weight', null=True)),
                ('fertType', models.TextField(blank=True, default=None, help_text='If category is fertilizer, specify type', null=True)),
                ('noOfRecipient', models.IntegerField(blank=True, default=None, help_text='Number of Farmer Recipients ', null=True)),
                ('municipality', models.ForeignKey(blank=True, db_column='municipality', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_support_municipality', to='location.city')),
                ('province', models.ForeignKey(blank=True, db_column='province', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_support_province', to='location.province')),
            ],
            options={
                'verbose_name': 'Production Support',
                'verbose_name_plural': 'Production Support',
                'ordering': ['province', 'municipality', 'yearDate'],
            },
        ),
        migrations.CreateModel(
            name='MachineryEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearDate', models.CharField(choices=[('2030', '2030'), ('2029', '2029'), ('2028', '2028'), ('2027', '2027'), ('2026', '2026'), ('2025', '2025'), ('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000'), ('1999', '1999'), ('1998', '1998'), ('1997', '1997'), ('1996', '1996'), ('1995', '1995'), ('1994', '1994'), ('1993', '1993'), ('1992', '1992'), ('1991', '1991'), ('1990', '1990')], help_text='Year', max_length=4)),
                ('activityTitle', models.TextField(blank=True, default=None, help_text='Title of Activity', null=True)),
                ('leadImplementer', models.CharField(blank=True, default=None, help_text='Lead Implementer', max_length=200, null=True)),
                ('agencyName', models.CharField(blank=True, default=None, help_text='Name of Agency', max_length=250, null=True)),
                ('machEquipType', models.CharField(blank=True, default=None, help_text='Machinery Type', max_length=500, null=True)),
                ('monthdayDate', models.CharField(blank=True, default=None, help_text='The month and day when the activity is conducted', max_length=50, null=True)),
                ('noOfUnits', models.IntegerField(blank=True, default=None, help_text='Number of units distributed', null=True)),
                ('fcaName', models.CharField(blank=True, default=None, help_text='Name of FCA', max_length=500, null=True)),
                ('municipality', models.ForeignKey(blank=True, db_column='municipality', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machinery_equipment_municipality', to='location.city')),
                ('province', models.ForeignKey(blank=True, db_column='province', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machinery_equipment_province', to='location.province')),
            ],
            options={
                'verbose_name': 'Machinery and Equipment',
                'verbose_name_plural': 'Machinery and Equipment',
                'ordering': ['province', 'municipality', 'yearDate'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAssistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearDate', models.CharField(choices=[('2030', '2030'), ('2029', '2029'), ('2028', '2028'), ('2027', '2027'), ('2026', '2026'), ('2025', '2025'), ('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000'), ('1999', '1999'), ('1998', '1998'), ('1997', '1997'), ('1996', '1996'), ('1995', '1995'), ('1994', '1994'), ('1993', '1993'), ('1992', '1992'), ('1991', '1991'), ('1990', '1990')], help_text='Year', max_length=4)),
                ('activityTitle', models.TextField(blank=True, default=None, help_text='Title of Activity', null=True)),
                ('leadImplementer', models.CharField(blank=True, default=None, help_text='Lead Implementer', max_length=200, null=True)),
                ('agencyName', models.CharField(blank=True, default=None, help_text='Name of Agency', max_length=250, null=True)),
                ('category', models.CharField(blank=True, default=None, help_text='Category', max_length=500, null=True)),
                ('monthdayDate', models.CharField(blank=True, default=None, help_text='The month and day when the activity is conducted', max_length=50, null=True)),
                ('totalAmount', models.FloatField(blank=True, default=None, help_text='Total amount', null=True)),
                ('noOfFarmersAvailed', models.IntegerField(blank=True, default=None, help_text='The number of farmers benefited by the activity', null=True)),
                ('municipality', models.ForeignKey(blank=True, db_column='municipality', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_assistance_municipality', to='location.city')),
                ('province', models.ForeignKey(blank=True, db_column='province', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_assistance_province', to='location.province')),
            ],
            options={
                'verbose_name': 'Financial Assistance',
                'verbose_name_plural': 'Financial Assistance',
                'ordering': ['province', 'municipality', 'yearDate'],
            },
        ),
        migrations.CreateModel(
            name='FacilityInfrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearDate', models.CharField(choices=[('2030', '2030'), ('2029', '2029'), ('2028', '2028'), ('2027', '2027'), ('2026', '2026'), ('2025', '2025'), ('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000'), ('1999', '1999'), ('1998', '1998'), ('1997', '1997'), ('1996', '1996'), ('1995', '1995'), ('1994', '1994'), ('1993', '1993'), ('1992', '1992'), ('1991', '1991'), ('1990', '1990')], help_text='Year', max_length=4)),
                ('projectTitle', models.TextField(blank=True, default=None, help_text='Project Title', null=True)),
                ('fundSource', models.CharField(blank=True, default=None, help_text='Fund Source', max_length=200, null=True)),
                ('amount', models.FloatField(blank=True, default=None, help_text='Amount', null=True)),
                ('category', models.CharField(blank=True, default=None, help_text='Category', max_length=200, null=True)),
                ('monthdayDate', models.CharField(blank=True, default=None, help_text='The month and day when the activity is conducted', max_length=50, null=True)),
                ('faciInfraType', models.CharField(blank=True, default=None, help_text='Type of facility or Infrastructure', max_length=500, null=True)),
                ('municipality', models.ForeignKey(blank=True, db_column='municipality', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_infrastructure_municipality', to='location.city')),
                ('province', models.ForeignKey(blank=True, db_column='province', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_infrastructure_province', to='location.province')),
            ],
            options={
                'verbose_name': 'Facilities and Infrastructure',
                'verbose_name_plural': 'Facilities and Infrastructure',
                'ordering': ['province', 'municipality', 'yearDate'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearDate', models.CharField(choices=[('2030', '2030'), ('2029', '2029'), ('2028', '2028'), ('2027', '2027'), ('2026', '2026'), ('2025', '2025'), ('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000'), ('1999', '1999'), ('1998', '1998'), ('1997', '1997'), ('1996', '1996'), ('1995', '1995'), ('1994', '1994'), ('1993', '1993'), ('1992', '1992'), ('1991', '1991'), ('1990', '1990')], help_text='Year', max_length=4)),
                ('activityTitle', models.TextField(blank=True, default=None, help_text='Title of Activity', null=True)),
                ('leadImplementer', models.CharField(blank=True, default=None, help_text='Lead Implementer', max_length=200, null=True)),
                ('agencyName', models.CharField(blank=True, default=None, help_text='Name of Agency', max_length=250, null=True)),
                ('category', models.CharField(blank=True, default=None, help_text='Category', max_length=250, null=True)),
                ('subCategory', models.CharField(blank=True, default=None, help_text='Sub-Category', max_length=250, null=True)),
                ('topics', models.CharField(blank=True, default=None, help_text='Topics', max_length=500, null=True)),
                ('monthdayDate', models.CharField(blank=True, default=None, help_text='The month and day when the activity is conducted', max_length=50, null=True)),
                ('duration', models.CharField(blank=True, default=None, help_text='Duration of the activity (Short-5days below, Long- longer than 5 days)', max_length=250, null=True)),
                ('noOfFarmersServed', models.IntegerField(blank=True, default=None, help_text='Number of Farmer served by the activity', null=True)),
                ('municipality', models.ForeignKey(blank=True, db_column='municipality', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extension_service_municipality', to='location.city')),
                ('province', models.ForeignKey(blank=True, db_column='province', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extension_service_province', to='location.province')),
            ],
            options={
                'verbose_name': 'Extention Service',
                'verbose_name_plural': 'Extension Service',
                'ordering': ['province', 'municipality', 'yearDate'],
            },
        ),
        migrations.CreateModel(
            name='CityMunicipalityProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfFarmers', models.IntegerField(blank=True, default=None, help_text='Number of Farmers', null=True)),
                ('totalRiceArea', models.FloatField(blank=True, default=None, help_text='Total Rice Area in Hectares (Physical)', null=True)),
                ('irrigated', models.FloatField(blank=True, default=None, help_text='Irrigated', null=True)),
                ('rainfed', models.FloatField(blank=True, default=None, help_text='Rainfed', null=True)),
                ('upland', models.FloatField(blank=True, default=None, help_text='Upland', null=True)),
                ('municipality', models.ForeignKey(blank=True, db_column='municipality', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_municipality_profile_municipality', to='location.city')),
                ('province', models.ForeignKey(blank=True, db_column='province', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_municipality_profile_province', to='location.province')),
            ],
            options={
                'verbose_name': 'City Municipality Profile',
                'verbose_name_plural': 'City Municipality Profile',
                'ordering': ['province', 'municipality'],
            },
        ),
        migrations.CreateModel(
            name='CityCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.TextField(blank=True, default=None, help_text='Coordinates', null=True)),
                ('municipality', models.ForeignKey(blank=True, db_column='municipality', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_coordinate_municipality', to='location.city')),
                ('province', models.ForeignKey(blank=True, db_column='province', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_coordinate_province', to='location.province')),
            ],
            options={
                'verbose_name': 'Coordinates - City',
                'verbose_name_plural': 'Coordinates - City',
                'ordering': ['province', 'municipality'],
            },
        ),
        migrations.CreateModel(
            name='AewProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='Name', max_length=100)),
                ('position', models.CharField(blank=True, default=None, help_text='Position', max_length=200, null=True)),
                ('sex', models.CharField(blank=True, default=None, help_text='Sex', max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, default=None, help_text='Age', null=True)),
                ('employmentStatus', models.CharField(blank=True, default=None, help_text='Employment Status', max_length=100, null=True)),
                ('yearsInService', models.IntegerField(blank=True, default=None, help_text='Years in Service', null=True)),
                ('birthdate', models.DateField(blank=True, default=None, help_text='Birthdate', null=True)),
                ('trainingsWanted', models.TextField(blank=True, default=None, help_text='Rice-related Trainings Wanted to Attend', null=True)),
                ('remarks', models.CharField(blank=True, default=None, help_text='Status of AEW (Type Old, New, Resigned, or Retired Staff)', max_length=50, null=True)),
                ('municipality', models.ForeignKey(blank=True, db_column='municipality', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aew_profile_municipality', to='location.city')),
                ('province', models.ForeignKey(blank=True, db_column='province', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aew_profile_province', to='location.province')),
            ],
            options={
                'verbose_name': 'AEW Profile',
                'verbose_name_plural': 'AEW Profile',
                'ordering': ['province', 'municipality'],
            },
        ),
    ]
