# Generated by Django 3.1 on 2023-07-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aewprofile',
            name='yearsInService',
            field=models.FloatField(blank=True, default=None, help_text='Years in Service', null=True),
        ),
    ]
